<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WebsiteSeeder extends Seeder
{
    public function run(): void
    {
        $websites = [
            // ==========================================
            // DATA 1: Poros Kalimantan
            // ==========================================
            [
                // Info Klien
                'client'           => 'PT. Media Poros BanuaKita',
                'jenis_klien'      => 'Media',
                'pic'              => 'Zepi Al Ayubi',
                'phone'            => '081351205145',
                'email'            => 'poroskalimantan@gmail.com',
                
                // Info Website
                'website'          => 'Poros Kalimantan',
                'url'              => 'https://poroskalimantan.com',
                'type'             => 'Berita',
                'technology'       => 'WordPress',
                'status'           => 'Active',
                'internal_pic'     => 'Iqbal',
                'service_package'  => null,
                'created_year'     => 2019,
                'note'             => null,

                // Info Domain
                'domain_name'      => 'poroskalimantan.com',
                'domain_provider'  => 'PlasaHosting.com',
                'domain_email'     => 'poroskalimantan@gmail.com',
                'domain_reg_date'  => '2019-10-24',
                'domain_exp_date'  => '2026-10-24',
                'domain_duration'  => 1,
                'is_auto_renew'    => true, 
                'domain_price'     => 229770,

                // Info Hosting
                'hosting_type'     => 'Dedicated Server',
                'hosting_provider' => 'OVHcloud',
                'hosting_package'  => 'Dedicated Server KS-3',
                'storage'          => '960GB',
                'ip_server'        => null,
                'location'         => 'Singapore',
                'hosting_email'    => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31', 
                'hosting_price'    => null,


                // Info Akses & Finansial
                'admin_url'        => null,
                'admin_username'   => null,
                'extra_access'     => null,
                'password_loc'     => null,
                'sell_price'       => null,
                'pay_system'       => null,
                'pay_status'       => null,
                'invoice_date'     => null,
                
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // ==========================================
            // DATA 2: Banjarbaru Klik
            // ==========================================
            [
                'client'           => 'PT Borneo Digital Media',
                'jenis_klien'      => 'Media',
                'pic'              => 'Ahmad Shalaby',
                'phone'            => '0895401638128',
                'email'            => null,
                
                'website'          => 'Banjarbaru Klik',
                'url'              => 'https://banjarbaruklik.com/',
                'type'             => 'Berita',
                'technology'       => 'WordPress',
                'status'           => 'Active',
                'internal_pic'     => 'Iqbal',
                'service_package'  => null,
                'created_year'     => 2015,
                'note'             => null,

                'domain_name'      => 'banjarbaruklik.com',
                'domain_provider'  => 'PlasaHosting.com',
                'domain_email'     => 'poroskalimantan@gmail.com',
                'domain_reg_date'  => '2015-12-21',
                'domain_exp_date'  => '2026-12-21',
                'domain_duration'  => 1,
                'is_auto_renew'    => true,
                'domain_price'     => 229770,

                'hosting_type'     => 'Dedicated Server',
                'hosting_provider' => 'OVHcloud',
                'hosting_package'  => 'Dedicated Server KS-3',
                'storage'          => '960GB',
                'ip_server'        => null,
                'location'         => 'Singapore',
                'hosting_email'    => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price'    => null,


                'admin_url'        => null,
                'admin_username'   => null,
                'extra_access'     => null,
                'password_loc'     => null,
                'sell_price'       => null,
                'pay_system'       => null,
                'pay_status'       => null,
                'invoice_date'     => null,
                
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // ==========================================
            // DATA 3: Martapura Klik
            // ==========================================
            [
                'client'           => 'PT Borneo Digital Media',
                'jenis_klien'      => 'Media',
                'pic'              => 'Ahmad Shalaby',
                'phone'            => '0895401638128',
                'email'            => null,
                
                'website'          => 'Martapura Klik',
                'url'              => 'https://martapuraklik.com/',
                'type'             => 'Berita',
                'technology'       => 'WordPress',
                'status'           => 'Active',
                'internal_pic'     => 'Iqbal',
                'service_package'  => null,
                'created_year'     => 2021,
                'note'             => null,

                'domain_name'      => 'martapuraklik.com',
                'domain_provider'  => 'Dewabiz.com',
                'domain_email'     => 'banjarbaruklik@gmail.com',
                'domain_reg_date'  => '2021-09-08',
                'domain_exp_date'  => '2026-09-07',
                'domain_duration'  => 1,
                'is_auto_renew'    => true,
                'domain_price'     => 250800,

                'hosting_type'     => 'Dedicated Server',
                'hosting_provider' => 'OVHcloud',
                'hosting_package'  => 'Dedicated Server KS-3',
                'storage'          => '960GB',
                'ip_server'        => null,
                'location'         => 'Singapore',
                'hosting_email'    => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price'    => null,


                'admin_url'        => null,
                'admin_username'   => null,
                'extra_access'     => null,
                'password_loc'     => null,
                'sell_price'       => null,
                'pay_system'       => null,
                'pay_status'       => null,
                'invoice_date'     => null,
                
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // ==========================================
            // DATA 4: Shalokal Indonesia
            // ==========================================
            [
                'client'           => 'PT. Shalokal Mediatama Indonesia',
                'jenis_klien'      => 'Media',
                'pic'              => 'Nanang Tri Hadi',
                'phone'            => '088247997828',
                'email'            => 'shalokalindonesia@gmail.com',
                
                'website'          => 'Shalokal Indonesia',
                'url'              => 'https://shalokalindonesia.com/',
                'type'             => 'Berita',
                'technology'       => 'WordPress',
                'status'           => 'Active',
                'internal_pic'     => 'Iqbal',
                'service_package'  => null,
                'created_year'     => 2022,
                'note'             => null,

                'domain_name'      => 'shalokalindonesia.com',
                'domain_provider'  => 'Domainesia.com',
                'domain_email'     => 'shalokalindonesia@gmail.com',
                'domain_reg_date'  => '2022-11-13',
                'domain_exp_date'  => '2026-11-13',
                'domain_duration'  => 1,
                'is_auto_renew'    => true,
                'domain_price'     => 209000,

                'hosting_type'     => 'Dedicated Server',
                'hosting_provider' => 'OVHcloud',
                'hosting_package'  => 'Dedicated Server KS-3',
                'storage'          => '960GB',
                'ip_server'        => null,
                'location'         => 'Singapore',
                'hosting_email'    => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price'    => null,


                'admin_url'        => null,
                'admin_username'   => null,
                'extra_access'     => null,
                'password_loc'     => null,
                'sell_price'       => null,
                'pay_system'       => null,
                'pay_status'       => null,
                'invoice_date'     => null,
                
                'created_at'       => now(),
                'updated_at'       => now(),
            ],

            // ==========================================
            // DATA 5: Pojok Digital Banua
            // ==========================================
            [
                'client'           => 'PT Pojok Digital Banua',
                'jenis_klien'      => 'Media',
                'pic'              => 'Shaiful Munir Yawafie',
                'phone'            => '085248690190',
                'email'            => 'pojokdigitalbanua@gmail.com',
                
                'website'          => 'Pojok Banua',
                'url'              => 'https://pojokbanua.com/',
                'type'             => 'Berita',
                'technology'       => 'WordPress',
                'status'           => 'Active',
                'internal_pic'     => 'Iqbal',
                'service_package'  => null,
                'created_year'     => 2020,
                'note'             => null,

                'domain_name'      => 'pojokbanua.com',
                'domain_provider'  => 'Domainesia.com',
                'domain_email'     => 'pojokdigitalbanua@gmail.com',
                'domain_reg_date'  => '2020-12-12',
                'domain_exp_date'  => '2028-12-12',
                'domain_duration'  => 5,
                'is_auto_renew'    => true,
                'domain_price'     => 155000,

                'hosting_type'     => 'Dedicated Server',
                'hosting_provider' => 'OVHcloud',
                'hosting_package'  => 'Dedicated Server KS-3',
                'storage'          => '960GB',
                'ip_server'        => null,
                'location'         => 'Singapore',
                'hosting_email'    => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price'    => null,


                'admin_url'        => null,
                'admin_username'   => null,
                'extra_access'     => null,
                'password_loc'     => null,
                'sell_price'       => null,
                'pay_system'       => null,
                'pay_status'       => null,
                'invoice_date'     => null,
                
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            // Data 6: PT. Borneo Klik Media - Energinesia
            [
                'client' => 'PT. Borneo Klik Media',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Energinesia',
                'url' => 'https://energinesia.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'energinesia.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2025-04-28',
                'domain_exp_date' => '2026-04-28',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 7: PT. Borneo Klik Media - Kalimantanesia
            [
                'client' => 'PT. Borneo Klik Media',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Kalimantanesia',
                'url' => 'https://kalimantanesia.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2023,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'kalimantanesia.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2023-10-18',
                'domain_exp_date' => '2026-10-18',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 8: PT. Borneo Klik Media - Parlemenesia
            [
                'client' => 'PT. Borneo Klik Media',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Parlemenesia',
                'url' => 'https://parlemenesia.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2023,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'parlemenesia.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2023-10-18',
                'domain_exp_date' => '2026-10-18',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 9: PT. Borneo Klik Media - Borneo Story
            [
                'client' => 'PT. Borneo Klik Media',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Borneo Story',
                'url' => 'https://borneostory.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2023,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'borneostory.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2023-10-18',
                'domain_exp_date' => '2026-10-18',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 10: PT. Borneo Klik Media - Detak Banua
            [
                'client' => 'PT. Borneo Klik Media',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Detak Banua',
                'url' => 'https://detakbanua.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2023,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'detakbanua.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2023-10-18',
                'domain_exp_date' => '2026-10-18',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 11: PT. Borneo Klik Media - Warta Kalimantan
            [
                'client' => 'PT. Borneo Klik Media',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Warta Kalimantan',
                'url' => 'https://wartakalimantan.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2023,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'wartakalimantan.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2023-10-18',
                'domain_exp_date' => '2026-10-18',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 12: Zepi Media - Daily Kalimantan
            [
                'client' => 'Zepi Media',
                'jenis_klien' => 'Media',
                'pic' => 'Zepi Al Ayubi',
                'phone' => '081351205145',
                'email' => null,
                'website' => 'Daily Kalimantan',
                'url' => 'https://dailykalimantan.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2023,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'dailykalimantan.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2023-11-03',
                'domain_exp_date' => '2026-11-03',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 13: PT. Kreativa Rama Nusantara - Nusa Banua TV
            [
                'client' => 'PT. Kreativa Rama Nusantara',
                'jenis_klien' => 'Media',
                'pic' => 'Rahmat Hidayatullah',
                'phone' => '082154057655',
                'email' => null,
                'website' => 'Nusa Banua TV',
                'url' => 'https://nusabanuatv.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2024,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'nusabanuatv.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2024-08-17',
                'domain_exp_date' => '2026-08-17',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 14: PT. Borneo Digital Media - Banjar Banar ID
            [
                'client' => 'PT. Borneo Digital Media',
                'jenis_klien' => 'Media',
                'pic' => 'Ahmad Shalaby',
                'phone' => '0895401638128',
                'email' => null,
                'website' => 'Banjar Banar ID',
                'url' => 'https://banjarbanar.id/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => 'Redirect ke BanjarbaruKlik',
                'domain_name' => 'banjarbanar.id',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2025-11-28',
                'domain_exp_date' => null, 
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Redirect ke BanjarbaruKlik',
                'hosting_package' => null,
                'hosting_provider' => null,
                'storage' => null,
                'ip_server' => null,
                'location' => null,
                'hosting_email' => null,
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => null,
                'pay_system' => null,
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 15: PT. Borneo Digital Media - Borneo Media
            [
                'client' => 'PT. Borneo Digital Media',
                'jenis_klien' => 'Instansi',
                'pic' => 'Ahmad Shalaby',
                'phone' => '0895401638128',
                'email' => null,
                'website' => 'Borneo Media',
                'url' => 'https://borneomedia.id/',
                'type' => 'Profil',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'borneomedia.id',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2025-10-20',
                'domain_exp_date' => '2026-10-20',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 250000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 16: PT. Saraba Digital Media - Saraba Banjar
            [
                'client' => 'PT. Saraba Digital Media',
                'jenis_klien' => 'Media',
                'pic' => 'M. Syahdansyah',
                'phone' => '082237112190',
                'email' => 'sarababanjarofficial@gmail.com',
                'website' => 'Saraba Banjar',
                'url' => 'https://sarababanjar.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2024,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'sarababanjar.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2024-12-02',
                'domain_exp_date' => '2026-12-02',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 250000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 17: Teman Karya Indonesia - Peristiwa Banua
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'Peristiwa Banua',
                'url' => 'https://peristiwabanua.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'peristiwabanua.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2025-06-28',
                'domain_exp_date' => '2026-06-28',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 18: Teman Karya Indonesia - Banjarbaru Medsos
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'Banjarbaru Medsos',
                'url' => 'https://banjarbarumedsos.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'banjarbarumedsos.com',
                'domain_provider' => 'WarnaHost.com',
                'domain_email' => 'banjardigital@gmail.com',
                'domain_reg_date' => '2025-06-28',
                'domain_exp_date' => '2026-06-29',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 19: Teman Karya Indonesia - Kalsel Go
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'Kalsel Go',
                'url' => 'http://kalselgo.id/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2024,
                'note' => null,
                'domain_name' => 'kalselgo.id',
                'domain_provider' => 'IDCloudHost.com',
                'domain_email' => 'uzanksalghifari@gmail.com',
                'domain_reg_date' => '2024-10-30',
                'domain_exp_date' => '2026-10-30',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => null,
                'hosting_package' => null,
                'hosting_provider' => null,
                'storage' => null,
                'ip_server' => null,
                'location' => null,
                'hosting_email' => null,
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => null,
                'pay_system' => null,
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 20: Teman Karya Indonesia - Banjarbaru 24 Jam
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'Banjarbaru 24 Jam',
                'url' => 'http://banjarbaru24jam.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => null,
                'domain_name' => 'banjarbaru24jam.com',
                'domain_provider' => 'Domainesia.com',
                'domain_email' => 'uzanksalghifari@gmail.com',
                'domain_reg_date' => '2025-11-28',
                'domain_exp_date' => null,
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 210000,
                'hosting_type' => null,
                'hosting_package' => null,
                'hosting_provider' => null,
                'storage' => null,
                'ip_server' => null,
                'location' => null,
                'hosting_email' => null,
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => null,
                'pay_system' => null,
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 21: Teman Karya Indonesia - HST Murakata
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'HST Murakata',
                'url' => 'https://hstmurakata.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2021,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'hstmurakata.com',
                'domain_provider' => 'Domainesia.com',
                'domain_email' => 'uzanksalghifari@gmail.com',
                'domain_reg_date' => '2021-11-30',
                'domain_exp_date' => null,
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 209000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 22: Teman Karya Indonesia - Peristiwa Update
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'Peristiwa Update',
                'url' => 'http://peristiwaupdate.id/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2025,
                'note' => null,
                'domain_name' => 'peristiwaupdate.id',
                'domain_provider' => 'Domainesia.com',
                'domain_email' => 'uzanksalghifari@gmail.com',
                'domain_reg_date' => '2025-11-28',
                'domain_exp_date' => null,
                'domain_duration' => 2,
                'is_auto_renew' => true,
                'domain_price' => 209000,
                'hosting_type' => null,
                'hosting_package' => null,
                'hosting_provider' => null,
                'storage' => null,
                'ip_server' => null,
                'location' => null,
                'hosting_email' => null,
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => null,
                'pay_system' => null,
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 23: Teman Karya Indonesia - Pesona Kalimantan
            [
                'client' => 'Teman Karya Indonesia',
                'jenis_klien' => 'Media',
                'pic' => 'Ujang',
                'phone' => '085975293256',
                'email' => null,
                'website' => 'Pesona Kalimantan',
                'url' => 'https://pesonakalimantan.com/',
                'type' => 'Berita',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2021,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'pesonakalimantan.com',
                'domain_provider' => 'Domainesia.com',
                'domain_email' => 'uzanksalghifari@gmail.com',
                'domain_reg_date' => '2021-12-14',
                'domain_exp_date' => null,
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 298000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Data 24: CV. Banjar Digital Media - Banjar Digital
            [
                'client' => 'CV. Banjar Digital Media',
                'jenis_klien' => 'Instansi',
                'pic' => 'Iqbal',
                'phone' => '082255021000',
                'email' => 'banjardigital@gmail.com',
                'website' => 'Banjar Digital',
                'url' => 'https://banjardigital.com/',
                'type' => 'Profil',
                'technology' => 'WordPress',
                'status' => 'Active',
                'internal_pic' => 'Iqbal',
                'created_year' => 2021,
                'note' => 'Pembayaran hosting 500ribu per bulan',
                'domain_name' => 'banjardigital.com',
                'domain_provider' => 'Domainesia.com',
                'domain_email' => 'uzanksalghifari@gmail.com',
                'domain_reg_date' => '2021-07-07',
                'domain_exp_date' => '2026-07-07',
                'domain_duration' => 1,
                'is_auto_renew' => true,
                'domain_price' => 209000,
                'hosting_type' => 'Dedicated Server',
                'hosting_package' => 'Dedicated Server KS-3',
                'hosting_provider' => 'OVHcloud',
                'storage' => '960GB',
                'ip_server' => null,
                'location' => 'Singapore',
                'hosting_email' => 'banjardigital@gmail.com',
                'hosting_exp_date' => '2025-12-31',
                'hosting_price' => null,
                'admin_url' => null,
                'admin_username' => null,
                'extra_access' => null,
                'password_loc' => null,
                'sell_price' => 500000,
                'pay_system' => 'Bulanan',
                'pay_status' => null,
                'invoice_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($websites as $website) {
            DB::table('websites')->insert($website);
        }
    }
}
