<?php

namespace Database\Seeders;

use App\Models\Website;
use Illuminate\Database\Seeder;

class WebsiteSeeder extends Seeder
{
    public function run(): void
    {
        Website::create([
            'client'           => 'PT Maju Jaya',
            'pic'              => 'Budi Santoso',
            'website'          => 'Maju Jaya Corp',
            'url'              => 'majujaya.com',
            'type'             => 'Profile',
            'technology'       => 'WordPress',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Pro',
            'created_year'     => '2023-01-15',
            'note'             => 'Klien lama',
            'phone'            => '08123456789',
            'email'            => 'budi@maju.com',
            'domain_provider'  => 'Niagahoster',
            'domain_email'     => 'admin@maju.com',
            'domain_reg_date'  => '2023-01-15',
            'domain_exp_date'  => '2024-01-15',
            'domain_price'     => 150000,
            'hosting_type'     => 'Dedicated Server',
            'hosting_provider' => 'DigitalOcean',
            'storage'          => 20,
            'ip_server'        => '192.168.1.1',
            'location'         => 'Singapore',
            'hosting_email'    => 'host@maju.com',
            'hosting_exp_date' => '2026-05-20',
            'hosting_price'    => 1200000,
            'admin_url'        => 'majujaya.com/wp-admin',
            'extra_access'     => 'cPanel',
            'password_loc'     => 'Bitwarden',
            'sell_price'       => 2500000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2023-01-10',
        ]);

        Website::create([
            'client'           => 'Warung Makan Enak',
            'pic'              => 'Siti Aminah',
            'website'          => 'Waroeng Enak',
            'url'              => 'waroengenak.id',
            'type'             => 'Blog',
            'technology'       => 'Laravel',
            'status'           => 'Suspend',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Basic',
            'created_year'     => '2022-11-20',
            'note'             => 'Menunggu pembayaran',
            'phone'            => '08567891234',
            'email'            => 'siti@enak.id',
            'domain_provider'  => 'Domainesia',
            'domain_email'     => 'siti@gmail.com',
            'domain_reg_date'  => '2022-11-20',
            'domain_exp_date'  => '2026-04-25',
            'domain_price'     => 250000,
            'hosting_type'     => 'Redirect',
            'hosting_provider' => 'Hostinger',
            'storage'          => 5,
            'ip_server'        => '103.11.22.33',
            'location'         => 'Jakarta',
            'hosting_email'    => 'siti@gmail.com',
            'hosting_exp_date' => '2026-05-01',
            'hosting_price'    => 500000,
            'admin_url'        => 'waroengenak.id/admin',
            'extra_access'     => 'FTP',
            'password_loc'     => 'Keepass',
            'sell_price'       => 1200000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Belum',
            'invoice_date'     => '2023-11-15',
        ]);
        Website::create([
            'client'           => 'Toko Elektronik Murah',
            'pic'              => 'Deni Kurniawan',
            'website'          => 'Elektro Murah',
            'url'              => 'elektromurah.com',
            'type'             => 'E-Commerce',
            'technology'       => 'WooCommerce',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Pro',
            'created_year'     => '2024-03-01',
            'note'             => 'Toko online elektronik rumahan',
            'phone'            => '08211223344',
            'email'            => 'deni@elektromurah.com',
            'domain_provider'  => 'Niagahoster',
            'domain_email'     => 'deni@gmail.com',
            'domain_reg_date'  => '2024-03-01',
            'domain_exp_date'  => '2025-03-01',
            'domain_price'     => 180000,
            'hosting_type'     => 'Cloud Hosting',
            'hosting_provider' => 'Niagahoster',
            'storage'          => 10,
            'ip_server'        => '103.22.44.55',
            'location'         => 'Jakarta',
            'hosting_email'    => 'deni@elektromurah.com',
            'hosting_exp_date' => '2026-04-11',
            'hosting_price'    => 800000,
            'admin_url'        => 'elektromurah.com/wp-admin',
            'extra_access'     => 'cPanel',
            'password_loc'     => 'Bitwarden',
            'sell_price'       => 3000000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2024-03-01',
        ]);

        Website::create([
            'client'           => 'CV Bintang Mandiri',
            'pic'              => 'Hendra Wijaya',
            'website'          => 'Bintang Mandiri',
            'url'              => 'bintangmandiri.co.id',
            'type'             => 'Profile',
            'technology'       => 'WordPress',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Business',
            'created_year'     => '2023-06-10',
            'note'             => 'Website company profile',
            'phone'            => '02198765432',
            'email'            => 'hendra@bintang.co.id',
            'domain_provider'  => 'Rumahweb',
            'domain_email'     => 'hendra@bintang.co.id',
            'domain_reg_date'  => '2023-06-10',
            'domain_exp_date'  => '2026-06-10',
            'domain_price'     => 90000,
            'hosting_type'     => 'Shared Hosting',
            'hosting_provider' => 'Rumahweb',
            'storage'          => 5,
            'ip_server'        => '180.232.11.44',
            'location'         => 'Yogyakarta',
            'hosting_email'    => 'hendra@bintang.co.id',
            'hosting_exp_date' => '2026-06-10',
            'hosting_price'    => 450000,
            'admin_url'        => 'bintangmandiri.co.id/wp-admin',
            'extra_access'     => 'cPanel',
            'password_loc'     => 'LastPass',
            'sell_price'       => 1800000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2023-06-05',
        ]);

        Website::create([
            'client'           => 'Klinik Sehat Sejahtera',
            'pic'              => 'dr. Rina Susanti',
            'website'          => 'Klinik Sehat',
            'url'              => 'kliniksehat.id',
            'type'             => 'Landing Page',
            'technology'       => 'HTML/CSS',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Basic',
            'created_year'     => '2024-01-20',
            'note'             => 'Hanya landing page, tanpa CMS',
            'phone'            => '02155667788',
            'email'            => 'rina@kliniksehat.id',
            'domain_provider'  => 'Domainesia',
            'domain_email'     => 'rina@gmail.com',
            'domain_reg_date'  => '2024-01-20',
            'domain_exp_date'  => '2026-01-20',
            'domain_price'     => 120000,
            'hosting_type'     => 'Shared Hosting',
            'hosting_provider' => 'Hostinger',
            'storage'          => 3,
            'ip_server'        => '31.220.1.90',
            'location'         => 'Amsterdam',
            'hosting_email'    => 'rina@kliniksehat.id',
            'hosting_exp_date' => '2026-07-20',
            'hosting_price'    => 350000,
            'admin_url'        => null,
            'extra_access'     => 'FTP',
            'password_loc'     => 'Bitwarden',
            'sell_price'       => 1500000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2024-01-15',
        ]);

        Website::create([
            'client'           => 'UD Sumber Rejeki',
            'pic'              => 'Pak Slamet',
            'website'          => 'Sumber Rejeki Store',
            'url'              => 'sumberrejeki.net',
            'type'             => 'E-Commerce',
            'technology'       => 'OpenCart',
            'status'           => 'InActive',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Pro',
            'created_year'     => '2022-05-01',
            'note'             => 'Website lama, perlu redesign',
            'phone'            => '08334455667',
            'email'            => 'slamet@sumberrejeki.net',
            'domain_provider'  => 'Niagahoster',
            'domain_email'     => 'slamet@gmail.com',
            'domain_reg_date'  => '2022-05-01',
            'domain_exp_date'  => '2025-05-01',
            'domain_price'     => 160000,
            'hosting_type'     => 'VPS',
            'hosting_provider' => 'DigitalOcean',
            'storage'          => 25,
            'ip_server'        => '178.62.33.12',
            'location'         => 'Singapore',
            'hosting_email'    => 'slamet@sumberrejeki.net',
            'hosting_exp_date' => '2026-04-20',
            'hosting_price'    => 1500000,
            'admin_url'        => 'sumberrejeki.net/admin',
            'extra_access'     => 'SSH',
            'password_loc'     => 'Keepass',
            'sell_price'       => 4000000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Belum',
            'invoice_date'     => '2024-05-01',
        ]);

        Website::create([
            'client'           => 'Yayasan Peduli Anak',
            'pic'              => 'Bu Dewi Rahayu',
            'website'          => 'Peduli Anak Foundation',
            'url'              => 'pedulianak.org',
            'type'             => 'Portal',
            'technology'       => 'WordPress',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Basic',
            'created_year'     => '2021-08-17',
            'note'             => 'Non-profit, harga khusus',
            'phone'            => '02177889900',
            'email'            => 'dewi@pedulianak.org',
            'domain_provider'  => 'Pandi',
            'domain_email'     => 'dewi@pedulianak.org',
            'domain_reg_date'  => '2021-08-17',
            'domain_exp_date'  => '2026-08-17',
            'domain_price'     => 75000,
            'hosting_type'     => 'Shared Hosting',
            'hosting_provider' => 'Rumahweb',
            'storage'          => 5,
            'ip_server'        => '180.232.55.10',
            'location'         => 'Yogyakarta',
            'hosting_email'    => 'dewi@pedulianak.org',
            'hosting_exp_date' => '2026-08-17',
            'hosting_price'    => 300000,
            'admin_url'        => 'pedulianak.org/wp-admin',
            'extra_access'     => null,
            'password_loc'     => 'Bitwarden',
            'sell_price'       => 900000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2025-08-10',
        ]);

        Website::create([
            'client'           => 'Studio Foto Cahaya',
            'pic'              => 'Andika Pratama',
            'website'          => 'Cahaya Studio',
            'url'              => 'cahayastudio.com',
            'type'             => 'Portfolio',
            'technology'       => 'Next.js',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Pro',
            'created_year'     => '2025-01-05',
            'note'             => 'Website portfolio fotografer profesional',
            'phone'            => '08567001122',
            'email'            => 'andika@cahayastudio.com',
            'domain_provider'  => 'Cloudflare',
            'domain_email'     => 'andika@gmail.com',
            'domain_reg_date'  => '2025-01-05',
            'domain_exp_date'  => '2026-01-05',
            'domain_price'     => 210000,
            'hosting_type'     => 'Cloud Hosting',
            'hosting_provider' => 'Vercel',
            'storage'          => 15,
            'ip_server'        => '76.76.21.21',
            'location'         => 'USA',
            'hosting_email'    => 'andika@cahayastudio.com',
            'hosting_exp_date' => '2026-04-28',
            'hosting_price'    => 960000,
            'admin_url'        => 'cahayastudio.com/admin',
            'extra_access'     => 'Vercel Dashboard',
            'password_loc'     => 'Bitwarden',
            'sell_price'       => 3500000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2025-01-03',
        ]);

        Website::create([
            'client'           => 'PT Logistik Cepat',
            'pic'              => 'Faisal Rahman',
            'website'          => 'Logistik Cepat',
            'url'              => 'logistik-cepat.id',
            'type'             => 'Portal',
            'technology'       => 'Laravel',
            'status'           => 'Active',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Business',
            'created_year'     => '2023-09-01',
            'note'             => 'Portal tracking pengiriman barang',
            'phone'            => '02130405060',
            'email'            => 'faisal@logistikcepat.id',
            'domain_provider'  => 'Domainesia',
            'domain_email'     => 'faisal@logistikcepat.id',
            'domain_reg_date'  => '2023-09-01',
            'domain_exp_date'  => '2025-09-01',
            'domain_price'     => 145000,
            'hosting_type'     => 'Dedicated Server',
            'hosting_provider' => 'AWS',
            'storage'          => 50,
            'ip_server'        => '54.169.100.22',
            'location'         => 'Singapore',
            'hosting_email'    => 'faisal@logistikcepat.id',
            'hosting_exp_date' => '2026-09-01',
            'hosting_price'    => 3600000,
            'admin_url'        => 'logistik-cepat.id/dashboard',
            'extra_access'     => 'AWS Console, SSH',
            'password_loc'     => 'LastPass',
            'sell_price'       => 8000000,
            'pay_system'       => 'Bulanan',
            'pay_status'       => 'Lunas',
            'invoice_date'     => '2025-09-01',
        ]);

        Website::create([
            'client'           => 'Bengkel Motor Jaya',
            'pic'              => 'Rudi Hartono',
            'website'          => 'Bengkel Jaya Online',
            'url'              => 'bengkeljaya.id',
            'type'             => 'Landing Page',
            'technology'       => 'HTML/CSS',
            'status'           => 'Suspend',
            'internal_pic'     => 'Iqbal',
            'service_package'  => 'Basic',
            'created_year'     => '2022-03-10',
            'note'             => 'Suspend karena belum perpanjang domain',
            'phone'            => '08199887766',
            'email'            => 'rudi@bengkeljaya.id',
            'domain_provider'  => 'Niagahoster',
            'domain_email'     => 'rudi@gmail.com',
            'domain_reg_date'  => '2022-03-10',
            'domain_exp_date'  => '2025-03-10',
            'domain_price'     => 95000,
            'hosting_type'     => 'Shared Hosting',
            'hosting_provider' => 'Hostinger',
            'storage'          => 3,
            'ip_server'        => '31.220.1.91',
            'location'         => 'Amsterdam',
            'hosting_email'    => 'rudi@gmail.com',
            'hosting_exp_date' => '2026-04-12',
            'hosting_price'    => 300000,
            'admin_url'        => null,
            'extra_access'     => 'FTP',
            'password_loc'     => null,
            'sell_price'       => 700000,
            'pay_system'       => 'Tahunan',
            'pay_status'       => 'Belum',
            'invoice_date'     => '2024-03-05',
        ]);
    }
}
